<?php
/**
 *
 * @package		Crowdfunding
 * @author 		siva_063at09
 * @copyright 	Copyright (c) 2012 {@link http://www.agriya.com/ Agriya Infoway}
 * @license		http://www.agriya.com/ Agriya Infoway Licence
 * @since 		2012-07-25
 *
 */
class FormFieldData {

	public $table = 'form_fields';

	public $records = array(
		array(
			'id' => '10',
			'name' => 'Project.feed_url',
			'display_text' => 'Feed URL',
			'label' => 'Feed URL',
			'type' => 'text',
			'info' => 'Automatically fetch updates from the given feed URL',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '15',
			'options' => '',
			'form_field_group_id' => '4',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '44',
			'name' => 'Upload_Media_File_1',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '17',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '24',
			'name' => 'Project.short_description',
			'display_text' => '',
			'label' => 'Short Description',
			'type' => 'textarea',
			'info' => 'This text will be used on share and RSS feeds.',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '2',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '23',
			'name' => 'Project.name',
			'display_text' => '',
			'label' => 'Name',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '0',
			'options' => '',
			'form_field_group_id' => '2',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '26',
			'name' => 'Attachment.filename',
			'display_text' => '',
			'label' => 'Upload Image',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => '',
			'form_field_group_id' => '2',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '27',
			'name' => 'Project.payment_method_id',
			'display_text' => '',
			'label' => 'Payment Method',
			'type' => 'select',
			'info' => 'For Fixed Funding project, fund will be captured only if it reached the needed amount. For Flexible Funding project, fund will be captured even if it does not reached the needed amount. But we charge a ##REACHED_FEE_AMOUNT##% fee if you reach your goal.',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '28',
			'name' => 'Project.address',
			'display_text' => '',
			'label' => 'Address',
			'type' => 'text',
			'info' => 'You must select address from autocomplete',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '10',
			'options' => '',
			'form_field_group_id' => '3',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '29',
			'name' => 'Project.address1',
			'display_text' => '',
			'label' => 'Address',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '11',
			'options' => '',
			'form_field_group_id' => '3',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '30',
			'name' => 'Project.country_id',
			'display_text' => '',
			'label' => 'Country',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '14',
			'options' => '',
			'form_field_group_id' => '3',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '31',
			'name' => 'State.name',
			'display_text' => '',
			'label' => 'State',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '13',
			'options' => '',
			'form_field_group_id' => '3',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '32',
			'name' => 'City.name',
			'display_text' => '',
			'label' => 'City',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '12',
			'options' => '',
			'form_field_group_id' => '3',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '33',
			'name' => 'Project.facebook_feed_url',
			'display_text' => 'Facebook feed URL',
			'label' => 'Facebook feed URL',
			'type' => 'text',
			'info' => 'You can enter facebook URL from which you want to show feeds.',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '33',
			'options' => '',
			'form_field_group_id' => '5',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '34',
			'name' => 'Project.twitter_feed_url',
			'display_text' => 'Twitter username',
			'label' => 'Twitter username',
			'type' => 'text',
			'info' => 'You can enter twitter username from which you want to show tweets. This widget is unavailable for private accounts.',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '34',
			'options' => '',
			'form_field_group_id' => '5',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '35',
			'name' => 'Project.needed_amount',
			'display_text' => '',
			'label' => 'Needed amount (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '5',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '36',
			'name' => 'Project.project_end_date',
			'display_text' => '',
			'label' => 'Project funding end date',
			'type' => 'date',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '9',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '37',
			'name' => 'Pledge.is_allow_over_funding',
			'display_text' => '',
			'label' => 'Allow overfunding',
			'type' => 'checkbox',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '6',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '38',
			'name' => 'Pledge.pledge_type_id',
			'display_text' => '',
			'label' => 'Pledge type',
			'type' => 'select',
			'info' => 'You can set pledge type as any, minimum, fixed, suggested amount that you want each member to pledge when joining your campaign. You select \"any\" option to let members pledge any amount.',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '7',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '39',
			'name' => 'ProjectReward.0.pledge_amount',
			'display_text' => '',
			'label' => 'Pledge amount ($)',
			'type' => 'text',
			'info' => 'Reward amount',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '28',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '40',
			'name' => 'ProjectReward.0.pledge_max_user_limit',
			'display_text' => '',
			'label' => 'Pledge max user limit',
			'type' => 'text',
			'info' => 'Maximum user allowed for this reward. Leave blank for no limit.',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '29',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '41',
			'name' => 'ProjectReward.0.reward',
			'display_text' => '',
			'label' => 'Reward',
			'type' => 'text',
			'info' => 'Reward description',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '26',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '42',
			'name' => 'Project.description',
			'display_text' => '',
			'label' => 'Description',
			'type' => 'textarea',
			'info' => 'Entered description will display in view page',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '25',
			'options' => '',
			'form_field_group_id' => '27',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '45',
			'name' => 'Description_1',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => 'Upload_Media_File_1',
			'depends_value' => '',
			'order' => '18',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '46',
			'name' => 'Upload_Media_File_2',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '19',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '47',
			'name' => 'Description_2',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => 'Upload_Media_File_2',
			'depends_value' => '',
			'order' => '20',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '48',
			'name' => 'Upload_Media_File_3',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '21',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '49',
			'name' => 'Description_3',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => 'Upload_Media_File_3',
			'depends_value' => '',
			'order' => '22',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '50',
			'name' => 'Upload_Media_File_4',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '23',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '51',
			'name' => 'Description_4',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => 'Upload_Media_File_4',
			'depends_value' => '',
			'order' => '24',
			'options' => '',
			'form_field_group_id' => '15',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '52',
			'name' => 'Project.video_embed_url',
			'display_text' => 'Video URL',
			'label' => 'Video URL',
			'type' => 'video',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '16',
			'options' => '',
			'form_field_group_id' => '17',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '53',
			'name' => 'LinkedIn_URL',
			'display_text' => 'LinkedIn URL',
			'label' => 'LinkedIn URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '35',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '54',
			'name' => 'Twitter_URL',
			'display_text' => 'Twitter URL',
			'label' => 'Twitter URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '36',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '55',
			'name' => 'MySpace_URL',
			'display_text' => 'MySpace URL',
			'label' => 'MySpace URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '37',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '56',
			'name' => 'Home_page_URL',
			'display_text' => 'Home page URL',
			'label' => 'Home page URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '38',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '57',
			'name' => 'Facebook_URL',
			'display_text' => 'Facebook URL',
			'label' => 'Facebook URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '39',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '59',
			'name' => 'IMDb_URL',
			'display_text' => 'IMDb URL',
			'label' => 'IMDb URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '40',
			'options' => '',
			'form_field_group_id' => '16',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '60',
			'name' => 'Pledge.min_amount_to_fund',
			'display_text' => '',
			'label' => 'Amount',
			'type' => 'text',
			'info' => 'amount',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '8',
			'options' => '',
			'form_field_group_id' => '6',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '61',
			'name' => 'Pledge.pledge_project_category_id',
			'display_text' => '',
			'label' => 'Project Category',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '2',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '63',
			'name' => 'ProjectReward.0.estimated_delivery_date',
			'display_text' => '',
			'label' => 'Estimated delivery date',
			'type' => 'date',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '27',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '64',
			'name' => 'ProjectReward.0.is_shipping',
			'display_text' => '',
			'label' => 'Shipping',
			'type' => 'checkbox',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '30',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '65',
			'name' => 'ProjectReward.0.is_having_additional_info',
			'display_text' => '',
			'label' => 'Additional Info.',
			'type' => 'checkbox',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '31',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '66',
			'name' => 'ProjectReward.0.additional_info_label',
			'display_text' => '',
			'label' => 'Additional info. label',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '1',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '32',
			'options' => '',
			'form_field_group_id' => '7',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '67',
			'name' => 'Project.feed_url',
			'display_text' => 'Feed URL',
			'label' => 'Feed URL',
			'type' => 'text',
			'info' => 'Automatically fetch updates from the given feed URL',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '15',
			'options' => '',
			'form_field_group_id' => '21',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '71',
			'name' => 'Upload_Media_File_1',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '17',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '72',
			'name' => 'Donate.donate_project_category_id',
			'display_text' => 'Project category',
			'label' => 'Project category',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '19',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '73',
			'name' => 'Project.short_description',
			'display_text' => 'Short description',
			'label' => 'Short description',
			'type' => 'textarea',
			'info' => 'This text will be used on share and RSS feeds.',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '19',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '74',
			'name' => 'Project.name',
			'display_text' => 'Name',
			'label' => 'Name',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '0',
			'options' => '',
			'form_field_group_id' => '19',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '75',
			'name' => 'Attachment.filename',
			'display_text' => 'Upload image',
			'label' => 'Upload image',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => '',
			'form_field_group_id' => '19',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '77',
			'name' => 'Project.address',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => 'You must select address from autocomplete',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '10',
			'options' => '',
			'form_field_group_id' => '20',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '78',
			'name' => 'Project.address1',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '11',
			'options' => '',
			'form_field_group_id' => '20',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '79',
			'name' => 'Project.country_id',
			'display_text' => 'Country',
			'label' => 'Country',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '14',
			'options' => '',
			'form_field_group_id' => '20',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '80',
			'name' => 'State.name',
			'display_text' => 'State',
			'label' => 'State',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '13',
			'options' => '',
			'form_field_group_id' => '20',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '81',
			'name' => 'City.name',
			'display_text' => 'City',
			'label' => 'City',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '12',
			'options' => '',
			'form_field_group_id' => '20',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '82',
			'name' => 'Project.facebook_feed_url',
			'display_text' => 'Facebook feed URL',
			'label' => 'Facebook feed URL',
			'type' => 'text',
			'info' => 'You can enter facebook URL from which you want to show feeds.',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '25',
			'options' => '',
			'form_field_group_id' => '22',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '83',
			'name' => 'Project.twitter_feed_url',
			'display_text' => 'Twitter username',
			'label' => 'Twitter username',
			'type' => 'text',
			'info' => 'You can enter twitter username from which you want to show tweets. This widget is unavailable for private accounts.',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '26',
			'options' => '',
			'form_field_group_id' => '22',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '85',
			'name' => 'Project.project_end_date',
			'display_text' => 'Donation end date',
			'label' => 'Donation end date',
			'type' => 'date',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '8',
			'options' => '',
			'form_field_group_id' => '23',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '86',
			'name' => 'Donate.is_allow_over_donating',
			'display_text' => 'Allow over donating',
			'label' => 'Allow Over Donation',
			'type' => 'checkbox',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '5',
			'options' => '',
			'form_field_group_id' => '23',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '88',
			'name' => 'Description_1',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => 'Upload_Media_File_1',
			'depends_value' => '',
			'order' => '18',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '89',
			'name' => 'Upload_Media_File_2',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '19',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '90',
			'name' => 'Description_2',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => 'Upload_Media_File_2',
			'depends_value' => '',
			'order' => '20',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '91',
			'name' => 'Upload_Media_File_3',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '21',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '92',
			'name' => 'Description_3',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => 'Upload_Media_File_3',
			'depends_value' => '',
			'order' => '22',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '93',
			'name' => 'Upload_Media_File_4',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '23',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '94',
			'name' => 'Description_4',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => 'Upload_Media_File_4',
			'depends_value' => '',
			'order' => '24',
			'options' => '',
			'form_field_group_id' => '24',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '95',
			'name' => 'Project.video_embed_url',
			'display_text' => 'Video URL',
			'label' => 'Video URL',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '16',
			'options' => '',
			'form_field_group_id' => '26',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '96',
			'name' => 'LinkedIn_URL',
			'display_text' => 'LinkedIn URL',
			'label' => 'LinkedIn URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '27',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '97',
			'name' => 'Twitter_URL',
			'display_text' => 'Twitter URL',
			'label' => 'Twitter URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '28',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '98',
			'name' => 'MySpace_URL',
			'display_text' => 'MySpace URL',
			'label' => 'MySpace URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '29',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '99',
			'name' => 'Home_page_URL',
			'display_text' => 'Home page URL',
			'label' => 'Home page URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '30',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '100',
			'name' => 'Facebook_URL',
			'display_text' => 'Facebook URL',
			'label' => 'Facebook URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '31',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '102',
			'name' => 'IMDb_URL',
			'display_text' => 'IMDb URL',
			'label' => 'IMDb URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '2',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '32',
			'options' => '',
			'form_field_group_id' => '25',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '105',
			'name' => 'Project.description',
			'display_text' => '',
			'label' => 'Description',
			'type' => 'textarea',
			'info' => 'Entered description will display in view page',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '9',
			'options' => '',
			'form_field_group_id' => '29',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '106',
			'name' => 'Project.needed_amount',
			'display_text' => '',
			'label' => 'Needed amount (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '2',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '23',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '113',
			'name' => 'Project.name',
			'display_text' => 'Name',
			'label' => 'Name',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '0',
			'options' => '',
			'form_field_group_id' => '30',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '114',
			'name' => 'Attachment.filename',
			'display_text' => 'Upload image',
			'label' => 'Upload image',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => '',
			'form_field_group_id' => '30',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '115',
			'name' => 'Lend.lend_project_category_id',
			'display_text' => 'Project category',
			'label' => 'Purpose',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '30',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '116',
			'name' => 'Project.short_description',
			'display_text' => 'Short description',
			'label' => 'Short description',
			'type' => 'textarea',
			'info' => 'This text will be used on share and RSS feeds.',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '30',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '117',
			'name' => 'Project.address',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => 'You must select address from autocomplete',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '10',
			'options' => '',
			'form_field_group_id' => '31',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '118',
			'name' => 'Project.address1',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '11',
			'options' => '',
			'form_field_group_id' => '31',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '119',
			'name' => 'Project.country_id',
			'display_text' => 'Country',
			'label' => 'Country',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '14',
			'options' => '',
			'form_field_group_id' => '31',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '120',
			'name' => 'State.name',
			'display_text' => 'State',
			'label' => 'State',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '13',
			'options' => '',
			'form_field_group_id' => '31',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '121',
			'name' => 'City.name',
			'display_text' => 'City',
			'label' => 'City',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '12',
			'options' => '',
			'form_field_group_id' => '31',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '122',
			'name' => 'Project.feed_url',
			'display_text' => 'Feed URL',
			'label' => 'Feed URL',
			'type' => 'text',
			'info' => 'Automatically fetch updates from the given feed URL',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '15',
			'options' => '',
			'form_field_group_id' => '32',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '123',
			'name' => 'Project.facebook_feed_url',
			'display_text' => 'Facebook feed URL',
			'label' => 'Facebook feed URL',
			'type' => 'text',
			'info' => 'You can enter facebook URL from which you want to show feeds.',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '25',
			'options' => '',
			'form_field_group_id' => '33',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '124',
			'name' => 'Project.twitter_feed_url',
			'display_text' => 'Twitter username',
			'label' => 'Twitter username',
			'type' => 'text',
			'info' => 'You can enter twitter username from which you want to show tweets. This widget is unavailable for private accounts.',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '26',
			'options' => '',
			'form_field_group_id' => '33',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '125',
			'name' => 'Project.project_end_date',
			'display_text' => 'Project end date',
			'label' => 'Project end date',
			'type' => 'date',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '8',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '126',
			'name' => 'Project.needed_amount',
			'display_text' => '',
			'label' => 'Loan amount (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '127',
			'name' => 'Upload_Media_File_1',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '17',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '128',
			'name' => 'Description_1',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => 'Upload_Media_File_1',
			'depends_value' => '',
			'order' => '18',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '129',
			'name' => 'Upload_Media_File_2',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '19',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '130',
			'name' => 'Description_2',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => 'Upload_Media_File_2',
			'depends_value' => '',
			'order' => '20',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '131',
			'name' => 'Upload_Media_File_3',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '21',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '132',
			'name' => 'Description_3',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => 'Upload_Media_File_3',
			'depends_value' => '',
			'order' => '22',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '133',
			'name' => 'Upload_Media_File_4',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '23',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '134',
			'name' => 'Description_4',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => 'Upload_Media_File_4',
			'depends_value' => '',
			'order' => '24',
			'options' => '',
			'form_field_group_id' => '35',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '135',
			'name' => 'LinkedIn_URL',
			'display_text' => 'LinkedIn URL',
			'label' => 'LinkedIn URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '27',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '136',
			'name' => 'Twitter_URL',
			'display_text' => 'Twitter URL',
			'label' => 'Twitter URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '28',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '137',
			'name' => 'MySpace_URL',
			'display_text' => 'MySpace URL',
			'label' => 'MySpace URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '29',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '138',
			'name' => 'Home_page_URL',
			'display_text' => 'Home page URL',
			'label' => 'Home page URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '30',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '139',
			'name' => 'Facebook_URL',
			'display_text' => 'Facebook URL',
			'label' => 'Facebook URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '31',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '140',
			'name' => 'IMDb_URL',
			'display_text' => 'IMDb URL',
			'label' => 'IMDb URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '32',
			'options' => '',
			'form_field_group_id' => '36',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '141',
			'name' => 'Project.video_embed_url',
			'display_text' => 'Video URL',
			'label' => 'Video URL',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '16',
			'options' => '',
			'form_field_group_id' => '37',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '145',
			'name' => 'Project.description',
			'display_text' => '',
			'label' => 'Description',
			'type' => 'textarea',
			'info' => 'Entered description will display in view page',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '9',
			'options' => '',
			'form_field_group_id' => '39',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '146',
			'name' => 'Project.name',
			'display_text' => 'Name',
			'label' => 'Name',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '0',
			'options' => '',
			'form_field_group_id' => '40',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '147',
			'name' => 'Attachment.filename',
			'display_text' => 'Upload image',
			'label' => 'Upload image',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => '',
			'form_field_group_id' => '40',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '148',
			'name' => 'Equity.equity_project_category_id',
			'display_text' => 'Project category',
			'label' => 'Project category',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '40',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '149',
			'name' => 'Project.short_description',
			'display_text' => 'Short description',
			'label' => 'Short description',
			'type' => 'textarea',
			'info' => 'This text will be used on share and RSS feeds.',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '40',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '150',
			'name' => 'Project.address',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => 'You must select address from autocomplete',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '10',
			'options' => '',
			'form_field_group_id' => '41',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '151',
			'name' => 'Project.address1',
			'display_text' => 'Address',
			'label' => 'Address',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '11',
			'options' => '',
			'form_field_group_id' => '41',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '152',
			'name' => 'Project.country_id',
			'display_text' => 'Country',
			'label' => 'Country',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '14',
			'options' => '',
			'form_field_group_id' => '41',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '153',
			'name' => 'State.name',
			'display_text' => 'State',
			'label' => 'State',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '13',
			'options' => '',
			'form_field_group_id' => '41',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '154',
			'name' => 'City.name',
			'display_text' => 'City',
			'label' => 'City',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '12',
			'options' => '',
			'form_field_group_id' => '41',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '155',
			'name' => 'Project.feed_url',
			'display_text' => 'Feed URL',
			'label' => 'Feed URL',
			'type' => 'text',
			'info' => 'Automatically fetch updates from the given feed URL',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '15',
			'options' => '',
			'form_field_group_id' => '42',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '156',
			'name' => 'Project.facebook_feed_url',
			'display_text' => 'Facebook feed URL',
			'label' => 'Facebook feed URL',
			'type' => 'text',
			'info' => 'You can enter facebook URL from which you want to show feeds.',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '25',
			'options' => '',
			'form_field_group_id' => '43',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '157',
			'name' => 'Project.twitter_feed_url',
			'display_text' => 'Twitter username',
			'label' => 'Twitter username',
			'type' => 'text',
			'info' => 'You can enter twitter username from which you want to show tweets. This widget is unavailable for private accounts.',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '26',
			'options' => '',
			'form_field_group_id' => '43',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '158',
			'name' => 'Project.project_end_date',
			'display_text' => 'Project end date',
			'label' => 'Project end date',
			'type' => 'date',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '8',
			'options' => '',
			'form_field_group_id' => '44',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '159',
			'name' => 'Project.needed_amount',
			'display_text' => '',
			'label' => 'Needed amount (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => 'Amount should be multiples of ##SITE_CURRENCY####MULTIPLE_AMOUNT##',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '44',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '160',
			'name' => 'Upload_Media_File_1',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '17',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '161',
			'name' => 'Description_1',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => 'Upload_Media_File_1',
			'depends_value' => '',
			'order' => '18',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '162',
			'name' => 'Upload_Media_File_2',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '19',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '163',
			'name' => 'Description_2',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => 'Upload_Media_File_2',
			'depends_value' => '',
			'order' => '20',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '164',
			'name' => 'Upload_Media_File_3',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '21',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '165',
			'name' => 'Description_3',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => 'Upload_Media_File_3',
			'depends_value' => '',
			'order' => '22',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '166',
			'name' => 'Upload_Media_File_4',
			'display_text' => 'Upload Media File',
			'label' => 'Upload Media File',
			'type' => 'file',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '23',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '167',
			'name' => 'Description_4',
			'display_text' => 'Description',
			'label' => 'Description',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => 'Upload_Media_File_4',
			'depends_value' => '',
			'order' => '24',
			'options' => '',
			'form_field_group_id' => '45',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '168',
			'name' => 'LinkedIn_URL',
			'display_text' => 'LinkedIn URL',
			'label' => 'LinkedIn URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '27',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '169',
			'name' => 'Twitter_URL',
			'display_text' => 'Twitter URL',
			'label' => 'Twitter URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '28',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '170',
			'name' => 'MySpace_URL',
			'display_text' => 'MySpace URL',
			'label' => 'MySpace URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '29',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '171',
			'name' => 'Home_page_URL',
			'display_text' => 'Home page URL',
			'label' => 'Home page URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '30',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '172',
			'name' => 'Facebook_URL',
			'display_text' => 'Facebook URL',
			'label' => 'Facebook URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '31',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '173',
			'name' => 'IMDb_URL',
			'display_text' => 'IMDb URL',
			'label' => 'IMDb URL',
			'type' => 'url',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '32',
			'options' => '',
			'form_field_group_id' => '46',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '174',
			'name' => 'Project.video_embed_url',
			'display_text' => 'Video URL',
			'label' => 'Video URL',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '4',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '16',
			'options' => '',
			'form_field_group_id' => '47',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '178',
			'name' => 'Project.description',
			'display_text' => '',
			'label' => 'Description',
			'type' => 'textarea',
			'info' => 'Entered description will display in view page',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '9',
			'options' => '',
			'form_field_group_id' => '49',
			'is_deletable' => '1',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => '1'
		),
		array(
			'id' => '179',
			'name' => 'Project.payment_method_id',
			'display_text' => '',
			'label' => 'Payment Method',
			'type' => 'select',
			'info' => 'For Fixed Funding project, fund will be captured only if it reached the needed amount. For Flexible Funding project, fund will be captured even if it does not reached the needed amount. But we charge a ##REACHED_FEE_AMOUNT##% fee if you reach your goal.',
			'project_type_id' => '4',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '44',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '180',
			'name' => 'Project.payment_method_id',
			'display_text' => '',
			'label' => 'Payment Method',
			'type' => 'select',
			'info' => 'For Fixed Lending project, lend will be captured only if it reached the needed amount. For Flexible Lending project, lend will be captured even if it does not reached the needed amount. But we charge a ##REACHED_FEE_AMOUNT##% fee if you reach your goal.',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '181',
			'name' => 'Lend.credit_score_id',
			'display_text' => 'Credit Score',
			'label' => 'Credit Score',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '182',
			'name' => 'Lend.loan_term_id',
			'display_text' => 'Loan Term',
			'label' => 'Loan Term',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '183',
			'name' => 'Lend.repayment_schedule_id',
			'display_text' => 'Repayment Schedule',
			'label' => 'Repayment Schedule',
			'type' => 'select',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '184',
			'name' => 'Lend.target_interest_rate',
			'display_text' => 'Interest Rate',
			'label' => 'Interest Rate',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => ''
		),
		array(
			'id' => '185',
			'name' => 'Project.payment_method_id',
			'display_text' => '',
			'label' => 'Payment Method',
			'type' => 'select',
			'info' => 'For Fixed Funding project, fund will be captured only if it reached the needed amount. For Flexible Funding project, fund will be captured even if it does not reached the needed amount. But we charge a ##REACHED_FEE_AMOUNT##% fee if you reach your goal.',
			'project_type_id' => '1',
			'required' => '1',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '34',
			'is_deletable' => '',
			'is_dynamic_field' => '',
			'is_active' => '',
			'is_show_display_text_field' => '',
			'is_editable' => ''
		),
		array(
			'id' => '186',
			'name' => 'Monthly_Income',
			'display_text' => 'Monthly Income (##SITE_CURRENCY##)',
			'label' => 'Monthly Income (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '1',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '187',
			'name' => 'Total_Expenses',
			'display_text' => 'Total Expenses (##SITE_CURRENCY##)',
			'label' => 'Total Expenses (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '2',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '188',
			'name' => 'Home_Ownership',
			'display_text' => 'Home Ownership',
			'label' => 'Home Ownership',
			'type' => 'radio',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '3',
			'options' => 'Yes, No',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '189',
			'name' => 'Length_of_Employment',
			'display_text' => 'Length of Employment',
			'label' => 'Length of Employment',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '4',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '190',
			'name' => 'Debt_to_Income',
			'display_text' => 'Debt to Income (##SITE_CURRENCY##)',
			'label' => 'Debt to Income (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '5',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '191',
			'name' => 'Employment_or_Selfemployment',
			'display_text' => 'Employment / Selfemployment',
			'label' => 'Employment / Selfemployment',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '6',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '192',
			'name' => 'Investments',
			'display_text' => 'Investments (##SITE_CURRENCY##)',
			'label' => 'Investments (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '7',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '193',
			'name' => 'Monthly_Expenses',
			'display_text' => 'Monthly Expenses (##SITE_CURRENCY##)',
			'label' => 'Monthly Expenses (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '8',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '194',
			'name' => 'Other_Loan_Repayments',
			'display_text' => 'Other Loan Repayments (##SITE_CURRENCY##)',
			'label' => 'Other Loan Repayments (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '9',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '195',
			'name' => 'Transport_Charges',
			'display_text' => 'Transport Charges (##SITE_CURRENCY##)',
			'label' => 'Transport Charges (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '10',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '196',
			'name' => 'Insurance',
			'display_text' => 'Insurance (##SITE_CURRENCY##)',
			'label' => 'Insurance (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '11',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '197',
			'name' => 'Courses_or_Schoolfees',
			'display_text' => 'Courses/School Fees (##SITE_CURRENCY##)',
			'label' => 'Courses/School Fees (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '12',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
		array(
			'id' => '198',
			'name' => 'Tax_and_NI_Provisions',
			'display_text' => 'Tax/NI Provisions (##SITE_CURRENCY##)',
			'label' => 'Tax/NI Provisions (##SITE_CURRENCY##)',
			'type' => 'text',
			'info' => '',
			'project_type_id' => '3',
			'required' => '',
			'depends_on' => '',
			'depends_value' => '',
			'order' => '13',
			'options' => '',
			'form_field_group_id' => '50',
			'is_deletable' => '1',
			'is_dynamic_field' => '1',
			'is_active' => '1',
			'is_show_display_text_field' => '1',
			'is_editable' => '1'
		),
	);

}
