<?php
/**
 *
 * @package		Crowdfunding
 * @author 		siva_063at09
 * @copyright 	Copyright (c) 2012 {@link http://www.agriya.com/ Agriya Infoway}
 * @license		http://www.agriya.com/ Agriya Infoway Licence
 * @since 		2012-07-25
 *
 */
class UserData {

	public $table = 'users';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2011-08-05 04:23:11',
			'modified' => '2012-11-03 11:14:48',
			'role_id' => '1',
			'username' => 'admin',
			'email' => 'productdemo.admin@gmail.com',
			'password' => '$1$Dm]T+^g$DMOW6j7MoaFoFYxeTkBGi/',
			'available_wallet_amount' => '0',
			'blocked_amount' => '0',
			'facebook_user_id' => '0',
			'timezone_id' => '0',
			'auto_detected_timezone_id' => '0',
			'user_openid_count' => '0',
			'user_login_count' => '0',
			'user_view_count' => '0',
			'project_fund_count' => '0',
			'project_count' => '0',
			'project_flag_count' => '0',
			'project_follower_count' => '0',
			'project_comment_count' => '0',
			'project_rating_count' => '0',
			'blog_count' => '0',
			'blog_comment_count' => '0',
			'unique_project_fund_count' => '0',
			'cookie_hash' => '',
			'cookie_time_modified' => '1970-01-01 00:00:00',
			'is_openid_register' => '',
			'is_agree_terms_conditions' => '1',
			'is_active' => '1',
			'is_email_confirmed' => '1',
			'is_affiliate_user' => '',
			'total_commission_pending_amount' => '0',
			'total_commission_canceled_amount' => '0',
			'total_commission_completed_amount' => '0',
			'commission_line_amount' => '0',
			'commission_withdraw_request_amount' => '0',
			'commission_paid_amount' => '0',
			'total_amount_withdrawn' => '0',
			'referred_purchase_count' => '0',
			'referred_project_count' => '0',
			'affiliate_refer_purchase_count' => '0',
			'ip_id' => '0',
			'last_login_ip_id' => '3',
			'last_logged_in_time' => '2012-12-19 12:51:58',
			'twitter_access_token' => '',
			'twitter_user_id' => '0',
			'twitter_access_key' => '0',
			'linkedin_user_id' => '0',
			'linkedin_access_token' => '',
			'is_linkedin_register' => '',
			'is_angellist_register' => '',
			'is_angellist_connected' => '',
			'angellist_user_id' => '0',
			'angellist_access_token' => '',
			'angellist_avatar_url' => '',
			'openid_user_id' => '0',
			'facebook_access_token' => '',
			'google_user_id' => '0',
			'google_access_token' => '',
			'yahoo_user_id' => '0',
			'yahoo_access_token' => '',
			'is_google_register' => '',
			'is_yahoo_register' => '',
			'is_facebook_register' => '',
			'is_twitter_register' => '',
			'is_facebook_connected' => '',
			'is_twitter_connected' => '',
			'is_google_connected' => '',
			'is_yahoo_connected' => '',
			'is_linkedin_connected' => '',
			'twitter_avatar_url' => '',
			'is_paid' => '',
			'site_state_id' => '',
			'sudopay_pay_key' => '',
			'sudopay_payment_id' => '0',
			'latitude' => '',
			'longitude' => '',
			'referred_by_user_id' => '0',
			'referred_by_user_count' => '0',
			'pwd_reset_token' => '',
			'pwd_reset_requested_date' => '1970-01-01 00:00:00',
			'security_question_id' => '0',
			'security_answer' => '',
			'total_withdraw_request_count' => '0',
			'is_accredited_investor' => '',
			'mobile_app_hash' => '',
			'mobile_app_time_modified' => '',
			'fb_friends_count' => '0',
			'twitter_followers_count' => '0',
			'linkedin_contacts_count' => '0',
			'google_contacts_count' => '0',
			'yahoo_contacts_count' => '0',
			'is_skipped_fb' => '1',
			'is_skipped_twitter' => '1',
			'is_skipped_linkedin' => '1',
			'is_skipped_google' => '1',
			'is_skipped_yahoo' => '1',
			'is_send_activities_mail' => '1',
			'total_needed_amount' => '0',
			'total_collected_amount' => '0',
			'total_funded_amount' => '0',
			'site_revenue' => '0',
			'invite_count' => '0',
			'user_avatar_source_id' => '1',
			'googleplus_user_id' => '0',
			'is_googleplus_register' => '',
			'is_googleplus_connected' => '',
			'googleplus_contacts_count' => '0',
			'googleplus_avatar_url' => '',
			'withdrawn_no_of_loans' => '0',
			'withdrawn_average_rate' => '0',
			'withdrawn_total_lent' => '0',
			'withdrawn_total_capital_returned' => '0',
			'withdrawn_total_interest_returned' => '0',
			'collection_no_of_loans' => '0',
			'collection_average_rate' => '0',
			'collection_total_lent' => '0',
			'collection_total_capital_returned' => '0',
			'collection_total_interest_returned' => '0',
			'closed_no_of_loans' => '0',
			'closed_average_rate' => '0',
			'closed_total_lent' => '0',
			'closed_total_capital_returned' => '0',
			'closed_total_interest_returned' => '0',
			'default_no_of_loans' => '0',
			'default_average_rate' => '0',
			'default_total_lent' => '0',
			'default_total_capital_returned' => '0',
			'default_total_interest_returned' => '0',
			'is_idle' => '1',
			'is_funded' => '',
			'is_project_posted' => '',
			'is_engaged' => '',
			'google_avatar_url' => '',
			'linkedin_avatar_url' => '',
			'angellist_contacts_count' => '0',
			'activity_message_id' => '0',
			'sudopay_gateway_id' => '0',
			'sudopay_receiver_account_id' => '',
			'sudopay_revised_amount' => '0',
			'sudopay_token' => ''
		),
	);

}
