<?php
/**
 *
 * @package		Crowdfunding
 * @author 		siva_063at09
 * @copyright 	Copyright (c) 2012 {@link http://www.agriya.com/ Agriya Infoway}
 * @license		http://www.agriya.com/ Agriya Infoway Licence
 * @since 		2012-07-25
 *
 */
class FormFieldStepData {

	public $table = 'form_field_steps';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2012-12-03 05:45:32',
			'modified' => '2012-12-11 01:54:39',
			'name' => 'Basics',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '1',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '2',
			'created' => '2012-12-03 05:45:41',
			'modified' => '2012-12-11 01:54:39',
			'name' => 'Details',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '2',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '3',
			'created' => '2012-12-03 05:45:49',
			'modified' => '2012-12-11 01:54:39',
			'name' => 'Rewards',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '3',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '4',
			'created' => '2012-12-03 05:45:56',
			'modified' => '2012-12-11 01:54:39',
			'name' => 'Social',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '4',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '5',
			'created' => '2012-12-03 05:46:04',
			'modified' => '2012-12-11 01:54:39',
			'name' => 'Payout',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '5',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '1'
		),
		array(
			'id' => '6',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2012-12-11 02:17:29',
			'name' => 'Basics',
			'slug' => '',
			'project_type_id' => '2',
			'info' => '',
			'order' => '1',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '7',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2012-12-11 02:17:29',
			'name' => 'Details',
			'slug' => '',
			'project_type_id' => '2',
			'info' => '',
			'order' => '2',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '8',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2012-12-11 02:17:29',
			'name' => 'Social',
			'slug' => '',
			'project_type_id' => '2',
			'info' => '',
			'order' => '3',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '9',
			'created' => '0000-00-00 00:00:00',
			'modified' => '2012-12-11 02:17:29',
			'name' => 'Payout',
			'slug' => '',
			'project_type_id' => '2',
			'info' => '',
			'order' => '4',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '1'
		),
		array(
			'id' => '10',
			'created' => '2013-03-16 12:47:04',
			'modified' => '2013-03-16 12:47:02',
			'name' => 'Basics',
			'slug' => '',
			'project_type_id' => '3',
			'info' => '',
			'order' => '1',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '11',
			'created' => '2013-03-16 12:47:29',
			'modified' => '2013-03-16 12:47:34',
			'name' => 'Details',
			'slug' => '',
			'project_type_id' => '3',
			'info' => '',
			'order' => '2',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '12',
			'created' => '2013-03-16 12:49:03',
			'modified' => '2013-03-16 12:49:06',
			'name' => 'Social',
			'slug' => '',
			'project_type_id' => '3',
			'info' => '',
			'order' => '3',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '14',
			'created' => '2013-03-16 12:47:04',
			'modified' => '2013-03-16 12:47:02',
			'name' => 'Basics',
			'slug' => '',
			'project_type_id' => '4',
			'info' => '',
			'order' => '1',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '15',
			'created' => '2013-03-16 12:47:29',
			'modified' => '2013-03-16 12:47:34',
			'name' => 'Details',
			'slug' => '',
			'project_type_id' => '4',
			'info' => '',
			'order' => '2',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '16',
			'created' => '2013-03-16 12:49:03',
			'modified' => '2013-03-16 12:49:06',
			'name' => 'Social',
			'slug' => '',
			'project_type_id' => '4',
			'info' => '',
			'order' => '3',
			'is_deletable' => '0',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '0',
			'is_editable' => '1',
			'is_payout_step' => '0'
		),
		array(
			'id' => '20',
			'created' => '2013-04-09 13:13:56',
			'modified' => '2013-04-09 13:13:56',
			'name' => 'Payment',
			'slug' => '',
			'project_type_id' => '4',
			'info' => '',
			'order' => '4',
			'is_deletable' => '1',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '1',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
		array(
			'id' => '18',
			'created' => '2013-04-09 13:09:41',
			'modified' => '2013-04-09 13:09:41',
			'name' => 'Payment',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '6',
			'is_deletable' => '1',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '1',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
		array(
			'id' => '19',
			'created' => '2013-04-09 13:11:17',
			'modified' => '2013-04-09 13:11:17',
			'name' => 'Confirmation',
			'slug' => '',
			'project_type_id' => '1',
			'info' => '',
			'order' => '7',
			'is_deletable' => '1',
			'is_splash' => '1',
			'additional_info' => 'Admin will approve,  after confirmed your filled data',
			'is_payment_step' => '0',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
		array(
			'id' => '21',
			'created' => '2013-04-09 13:14:33',
			'modified' => '2013-04-09 13:14:33',
			'name' => 'Payment',
			'slug' => '',
			'project_type_id' => '3',
			'info' => '',
			'order' => '4',
			'is_deletable' => '1',
			'is_splash' => '0',
			'additional_info' => '',
			'is_payment_step' => '1',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
		array(
			'id' => '22',
			'created' => '2013-04-09 13:15:46',
			'modified' => '2013-04-09 13:15:46',
			'name' => 'Confirmation',
			'slug' => '',
			'project_type_id' => '4',
			'info' => 'Admin will approve,  after confirmed your filled data',
			'order' => '5',
			'is_deletable' => '1',
			'is_splash' => '1',
			'additional_info' => 'Admin will approve,  after confirmed your filled data',
			'is_payment_step' => '0',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
		array(
			'id' => '23',
			'created' => '2013-04-09 13:16:01',
			'modified' => '2013-04-09 13:16:01',
			'name' => 'Confirmation',
			'slug' => '',
			'project_type_id' => '3',
			'info' => 'Admin will approve,  after confirmed your filled data',
			'order' => '5',
			'is_deletable' => '1',
			'is_splash' => '1',
			'additional_info' => 'Admin will approve,  after confirmed your filled data',
			'is_payment_step' => '0',
			'is_editable' => '0',
			'is_payout_step' => '0'
		),
	);

}
